# Generated by Django 5.1.2 on 2025-08-01 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='technologies_used',
        ),
        migrations.AddField(
            model_name='experience',
            name='technologies_used',
            field=models.ManyToManyField(blank=True, related_name='experiences', to='core.skill'),
        ),
    ]
