# Generated by Django 4.2.23 on 2025-09-03 16:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_experience_technologies_used_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certification',
            name='image',
        ),
        migrations.AddField(
            model_name='certification',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='certifications/', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
    ]
