# Generated by Django 5.2.5 on 2025-09-03 19:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_certification_image_certification_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certification',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='certifications/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])]),
        ),
    ]
